version: '3.9'
services:
  apollo:
    image: "vlauciani/caravel-apollo:${APOLLO_VERSION:-latest}"
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
    networks:
      - network-caravel-apollo
  hyp2000:
    image: ingv/hyp2000:latest
    entrypoint: bash
    command: -c "tar -C /opt/ew_env -xzf /app/apollo/soft/go1.20.1.linux-amd64.tar.gz && PATH=\"$PATH:/opt/ew_env/go/bin\" && go install github.com/msoap/shell2http@latest && PATH=\"$PATH:$$(go env GOPATH)/bin\" && shell2http -port 8080 -form -include-stderr --shell=\"bash\" -cgi /get '. /home/ew/.bashrc && cd /app/storage/app/data/hyp2000/$${v_dir}/input && cat italy2000.hyp | hyp2000 > ../output/output.log 2> ../output/output.err && cd ../output && cat hypo.arc | tr \"\\0\" \" \" | ew2openapi TYPE_HYP2000ARC - hypo.json || (echo \"Status:503\\n\\n$$(cat /app/storage/app/data/hyp2000/$${v_dir}/output/output.err)\")'"
    #command: -c "rm -rf /usr/local/go && tar -C /usr/local -xzf /app/storage/go1.20.1.linux-amd64.tar.gz && PATH=\"$PATH:/usr/local/go/bin\" && go install github.com/msoap/shell2http@latest && PATH=\"$PATH:$$(go env GOPATH)/bin\" && shell2http -port 8080 -form -include-stderr -cgi /get '. /root/.bashrc && export DIR_DATA=/app/storage/app/data/hyp2000/$${v_dir} && /opt/entrypoint.sh italy2000.hyp > /app/storage/app/data/hyp2000/$${v_dir}/output.log 2>/app/storage/app/data/hyp2000/$${v_dir}/output.err && mv /app/storage/app/data/hyp2000/$${v_dir}/output.* /app/storage/app/data/hyp2000/$${v_dir}/output/ || (mv /app/storage/app/data/hyp2000//app/storage/app/data/hyp2000/$${v_dir}/output.* /app/storage/app/data/hyp2000/$${v_dir}/output/ && echo \"Status:503\\n\\n$$(cat /app/storage/app/data/hyp2000//app/storage/app/data/hyp2000//app/storage/app/data/hyp2000//app/storage/app/data/hyp2000/$${v_dir}/output/output.err)\")'"
    networks:
      - network-caravel-apollo
    environment:
      - EW_HOSTNAME=hew
  pyml:
    image: ingv/pyml:latest
    entrypoint: bash
    command: -c "rm -rf /usr/local/go && tar -C /usr/local -xzf /app/apollo/soft/go1.20.1.linux-amd64.tar.gz && PATH=\"$PATH:/usr/local/go/bin\" && go install github.com/msoap/shell2http@latest && PATH=\"$PATH:$$(go env GOPATH)/bin\" && shell2http -port 8080 -form -include-stderr -cgi /get '/opt/entrypoint.sh --json /app/storage/app/data/pyml/$${v_dir}/input.json  > /app/storage/app/data/pyml/$${v_dir}/output.log 2>/app/storage/app/data/pyml/$${v_dir}/output.err || (echo \"Status:503\\n\\n$$(cat /app/storage/app/data/pyml/$${v_dir}/output/output.err)\")'"
    networks:
      - network-caravel-apollo
  redis:
    image: redis:7.0.7
    volumes:
      - 'redis.data:/data'
    command: --requirepass r3d15
    networks:
      - network-caravel-apollo
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
volumes:
  redis.data:
    driver: local
networks:
  network-caravel-apollo:
    driver: bridge
