version: '3.9'
services:
  apollo:
    build:
      context: ./
      dockerfile: ./docker/apollo/Dockerfile
      target: apollo-dev
      cache_from:
        - "vlauciani/caravel-apollo:latest"
    ports:
      - 8586:80
    volumes:
      - ./:/app:cached
  docker-in-docker:
    volumes:
      - ./:/app:cached
