version: '3.9'
services:
  apollo:
    build:
      context: ./
      dockerfile: ./docker/apollo/Dockerfile
      target: apollo-dev
      cache_from:
        - "vlauciani/caravel-apollo:latest"
    volumes:
      - ./:/app:cached
    #environment:
    #  - DB_HOST=casa
    ports:
      - 8586:80
  docker-in-docker:
    volumes:
      - docker-in-docker.data:/certs/client
      - ./:/app:cached
