version: '3.9'
services:
  apollo:
    build:
      context: ./
      dockerfile: ./docker/apollo/Dockerfile
      target: apollo-dev
      cache_from:
        - "vlauciani/caravel-apollo:latest"
    ports:
      - 8586:80
    volumes:
      - ./:/app:cached
  hyp2000:
    volumes:
      - ./storage:/app/storage:cached
  pyml:
    volumes:
      - ./storage:/app/storage:cached
  redis:
    ports:
      - 6386:6379
