version: '3.9'
services:
  apollo:
    image: "vlauciani/caravel-apollo:${APOLLO_VERSION:-latest}"
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
    networks:
      - network-caravel-apollo
  redis:
    image: redis:7.0.7
    volumes:
      - 'redis.data:/data'
    networks:
      - network-caravel-apollo
    command: --requirepass r3d15
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
volumes:
  redis.data:
    driver: local
networks:
  network-caravel-apollo:
    driver: bridge
