version: '3.9'
services:
  apollo:
    build:
      context: ./
      dockerfile: ./docker/apollo/Dockerfile
      target: apollo-prod
      cache_from:
        - "vlauciani/caravel-apollo:latest"
    ports:
      - 8086:80
    volumes:
      - apollo.storage:/app/storage:cached
  hyp2000:
    volumes:
      - apollo.storage/:/app/storage:cached
  pyml:
    volumes:
      - apollo.storage/:/app/storage:cached
volumes:
  apollo.storage:
    driver: local
